# netlify.toml
[build]
  publish = "."

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Configuração para forms
[[headers]]
  for = "/*"
  [headers.values]
    "X-Frame-Options" = "DENY"
    "X-XSS-Protection" = "1; mode=block"