<<<<<<< HEAD
[build]
=======
﻿[build]
>>>>>>> a23cc1c99ff3d2c20ba42de4282a8f012b38e4d0
  publish = "."
  command = "echo 'No build command needed'"

[build.environment]
  NODE_VERSION = "18"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

<<<<<<< HEAD
# Configuração para forms
=======
>>>>>>> a23cc1c99ff3d2c20ba42de4282a8f012b38e4d0
[[headers]]
  for = "/*"
  [headers.values]
    "X-Frame-Options" = "DENY"
    "X-XSS-Protection" = "1; mode=block"
    "Cache-Control" = "public, max-age=3600"

<<<<<<< HEAD
# Cache para assets estáticos
=======
>>>>>>> a23cc1c99ff3d2c20ba42de4282a8f012b38e4d0
[[headers]]
  for = "/css/*"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000"

[[headers]]
  for = "/js/*"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000"

[[headers]]
  for = "/images/*"
  [headers.values]
<<<<<<< HEAD
    "Cache-Control" = "public, max-age=31536000"
=======
    "Cache-Control" = "public, max-age=31536000"
>>>>>>> a23cc1c99ff3d2c20ba42de4282a8f012b38e4d0
